---
 - name: Creating user Panda and group panada
   group:
     name: "panda"
     state: present


 - name: Creating user pnada
   user:
     name: panda
     shell: /bin/bash
     groups: sudo,panda
     append: yes

 - name: auth keys
   ansible.posix.authorized_key:
     user: panda
     state: present
     key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"
