---
- name: Creating user Panda and group panada 
  hosts: local
  connection: local
  become: true
  
  group:
    name: panda
    state: present
  
- name: Creating user pnada
  user: panda
  shell: /bin/bash
  groups:
    - panda
    - sudo

- name: Auth
  authorized_key:
  user: panda
  state: present
  key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"