- name: Install tools 
  hosts: local
  connection: local
  become: true

  tasks:
    - name: Install unzip 
      package:
        name: unzip
        state: present
    - name: Install net-tools
      package:
        name: net-tools
        state: present

